In [1]:
import numpy as np

In [2]:
array_empty=np.empty((3,2))

In [3]:
array_empty

array([[9.34603679e-307, 1.11260144e-306],
       [1.33511562e-306, 4.67291993e-307],
       [4.00536722e-307, 6.89796663e-307]])

In [4]:
#identity matrix

In [5]:
array_of_eye=np.eye(4)

In [6]:
array_of_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
array_of_odds=np.arange(1,30,2)

In [8]:
array_of_odds

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [9]:
array_of_floats=np.arange(0,4,0.2)

In [10]:
array_of_floats

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8])

In [11]:
array_of_odds.shape

(15,)

In [14]:
b=array_of_odds.reshape(3,5)

In [15]:
b

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29]])

In [17]:
b.shape

(3, 5)

In [18]:
c=array_of_odds.reshape(3,5,1)

In [19]:
c

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]],

       [[21],
        [23],
        [25],
        [27],
        [29]]])

In [21]:
threedimensional_array=np.arange(16).reshape(2,2,4)

In [22]:
threedimensional_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [23]:
threedimensional_array.shape

(2, 2, 4)